@echo off
rem Generated by ant, January 5 2011.
rem Note that a Java runtime should be on the path.
rem The current directory should be root of the nxt install.

java -Xms128m -Xmx1024m -cp lib;lib/nxt.jar;lib/jdom.jar;lib/JMF/lib/jmf.jar;lib/pnuts.jar;lib/resolver.jar;lib/xalan.jar;lib/xercesImpl.jar;lib/xml-apis.jar;lib/jmanual.jar;lib/jh.jar;lib/helpset.jar;lib/poi.jar;lib/eclipseicons.jar;lib/icons.jar;lib/forms.jar;lib/looks.jar;lib/necoderHelp.jar;lib/videolabelerHelp.jar;lib/dacoderHelp.jar;lib/testcoderHelp.jar;lib/prefuse.jar net.sourceforge.nite.nxt.GUI -corpus Data/meta/genesis.xml %*
		
