/* Generated By:JJTree: Do not edit this line. NodeQuery.java */

package net.sourceforge.nite.search;

/**
 * Generated by the
 * <a href="http://www.webgain.com/products/java_cc/" target="_blank">JavaCC</a>
 * tool JJTree.
 */
public class NodeQuery extends SimpleNode {
  public NodeQuery(int id) {
    super(id);
  }

  public NodeQuery(Parser p, int id) {
    super(p, id);
  }

}
