/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */
package net.sourceforge.nite.search;

public interface ParserConstants {

  int EOF = 0;
  int NOT = 7;
  int IMPLICATION = 8;
  int AND = 9;
  int OR = 10;
  int EQ = 11;
  int NE = 12;
  int GE = 13;
  int LE = 14;
  int GT = 15;
  int LT = 16;
  int EQREGEXP = 17;
  int NEREGEXP = 18;
  int TEXT = 19;
  int START = 20;
  int END = 21;
  int DURATION = 22;
  int CENTER = 23;
  int ID = 24;
  int TIMED = 25;
  int LEFT = 26;
  int RIGHT = 27;
  int DOMINANCE = 28;
  int POINTER = 29;
  int PRECEDENCE = 30;
  int OVERLAPS_LEFT = 31;
  int LEFT_ALIGNED_WITH = 32;
  int RIGHT_ALIGNED_WITH = 33;
  int INCLUDES = 34;
  int SAME_EXTENT_AS = 35;
  int OVERLAPS_WITH = 36;
  int CONTACT_WITH = 37;
  int PRECEDES = 38;
  int VALUE = 39;
  int REGEXP = 40;
  int EXISTS = 41;
  int FORALL = 42;
  int VARATR = 43;
  int VAR = 44;
  int TYPE = 45;
  int NUMBER = 46;
  int LETTER = 47;
  int DIGIT = 48;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<NOT>",
    "<IMPLICATION>",
    "<AND>",
    "<OR>",
    "<EQ>",
    "<NE>",
    "<GE>",
    "<LE>",
    "<GT>",
    "<LT>",
    "\"~\"",
    "\"!~\"",
    "<TEXT>",
    "<START>",
    "<END>",
    "<DURATION>",
    "<CENTER>",
    "<ID>",
    "<TIMED>",
    "<LEFT>",
    "<RIGHT>",
    "\"^\"",
    "\">\"",
    "\"<\"",
    "<OVERLAPS_LEFT>",
    "<LEFT_ALIGNED_WITH>",
    "<RIGHT_ALIGNED_WITH>",
    "<INCLUDES>",
    "<SAME_EXTENT_AS>",
    "<OVERLAPS_WITH>",
    "<CONTACT_WITH>",
    "<PRECEDES>",
    "<VALUE>",
    "<REGEXP>",
    "<EXISTS>",
    "<FORALL>",
    "<VARATR>",
    "<VAR>",
    "<TYPE>",
    "<NUMBER>",
    "<LETTER>",
    "<DIGIT>",
    "\"::\"",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\":\"",
  };

}
