/* Generated By:JJTree: Do not edit this line. C:/Programme/eclipse/workspace/nxt_search/net/sourceforge/nite/search\ParserTreeConstants.java */

package net.sourceforge.nite.search;

public interface ParserTreeConstants
{
  public int JJTQUERY = 0;
  public int JJTSIMPLEQUERY = 1;
  public int JJTLOGICAL = 2;
  public int JJTCONDITION = 3;


  public String[] jjtNodeName = {
    "Query",
    "SimpleQuery",
    "Logical",
    "Condition",
  };
}
